# Generated by Django 2.2.2 on 2019-06-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ads_Name', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
            ],
        ),
    ]
